FROM python:3.10-slim-buster

ENV PYTHONUNBUFFERED 1
ENV MUJOCO_GL egl
ADD ./agent /
ADD ./utils /
ADD ./requirements/neuroflex.txt /
RUN pip install --upgrade pip
RUN pip install -r neuroflex.txt
CMD [ "python", "agent_neuroflex.py" ]
